export const regions = [
  { id: "AU", label: "Australia", short: "AU" },
  { id: "US", label: "United States", short: "US" },
  { id: "UK", label: "United Kingdom", short: "UK" },
  { id: "CA", label: "Canada", short: "CA" },
  { id: "SEA", label: "东南亚", short: "SEA" },
  { id: "CN", label: "中国菜", short: "CN" },
];

const dishAsset = (filename) => `${import.meta.env.BASE_URL}dishes/${filename}`;

const dishImages = {
  AU: dishAsset("australia-parmigiana.png"),
  US: dishAsset("us-mac-cheese.png"),
  UK: dishAsset("uk-tikka-masala.png"),
  CA: dishAsset("canada-maple-salmon.png"),
  SEA: dishAsset("sea-basil-chicken.png"),
  CN: dishAsset("cn-home-cooking.png"),
};

const makeRecipe = (region, recipe) => ({
  region,
  image: dishImages[region],
  difficulty: "新手友好",
  servings: "1–2 人",
  ...recipe,
});

export const starterRecipes = [
  makeRecipe("AU", {
    id: "au-parmigiana",
    title: "脆皮帕玛鸡",
    english: "Chicken Parmigiana",
    category: "MAIN",
    time: "28 min",
    cost: "约 A$9.80",
    ingredients: [
      ["鸡胸肉", "1 块", "拍薄更易熟"],
      ["面包糠", "4 汤匙", "普通款即可"],
      ["意面番茄酱", "5 汤匙", "留一点蘸食"],
      ["马苏里拉芝士", "60 g", "刨丝"],
      ["生菜或沙拉包", "1 小把", "配菜"],
    ],
    steps: [
      "鸡胸拍薄，撒盐与黑胡椒，薄薄沾水后裹面包糠。",
      "平底锅中火加油，每面煎 4–5 分钟至金黄熟透。",
      "铺番茄酱和芝士，盖锅盖小火焖 2 分钟。",
      "配即食沙拉装盘，锅里剩余酱汁一起淋上。",
    ],
    tip: "没有烤箱也没关系，最后盖锅盖就是留学生版的上火烘烤。",
  }),
  makeRecipe("AU", {
    id: "au-barramundi",
    image: dishAsset("au-barramundi.png"),
    title: "柠檬黄油澳肺鱼",
    english: "Lemon Butter Barramundi",
    category: "SEAFOOD",
    time: "18 min",
    cost: "约 A$11.20",
    ingredients: [
      ["澳肺鱼鱼排", "1 块", "可换任意白肉鱼"],
      ["黄油", "15 g", "无盐或有盐均可"],
      ["柠檬", "1/2 个", "皮屑也能用"],
      ["冷冻四季豆", "1 杯", "无需解冻"],
      ["微波米饭", "1 盒", "快速主食"],
    ],
    steps: [
      "鱼排擦干，两面撒盐和黑胡椒。",
      "锅热后少油，鱼皮朝下煎 4 分钟，翻面再煎 2 分钟。",
      "加入黄油、柠檬汁和四季豆，轻轻浇汁 2 分钟。",
      "微波米饭加热，鱼排与豆角一起装盘。",
    ],
    tip: "鱼皮下锅后先别动，等它自己容易铲起时再翻面。",
  }),
  makeRecipe("AU", {
    id: "au-sausage-pasta",
    image: dishAsset("au-sausage-pasta.png"),
    title: "一锅香肠番茄意面",
    english: "One-pan Sausage Pasta",
    category: "PASTA",
    time: "24 min",
    cost: "约 A$7.60",
    ingredients: [
      ["牛肉香肠", "2 根", "剪成小段"],
      ["短意面", "120 g", "通心粉最好"],
      ["罐装番茄", "1/2 罐", "碎番茄"],
      ["洋葱", "1/2 个", "切丁"],
      ["菠菜", "1 大把", "最后再放"],
    ],
    steps: [
      "香肠段下锅煎出油脂，加入洋葱炒软。",
      "倒入番茄、意面和 300 ml 水，大火煮开。",
      "转中火搅拌 12 分钟，水少就补一点。",
      "拌入菠菜与黑胡椒，关火静置 2 分钟。",
    ],
    tip: "全程只洗一口锅，剩下的一半罐头番茄可冷冻。",
  }),

  makeRecipe("US", {
    id: "us-mac-cheese",
    title: "奶油芝士通心粉",
    english: "Stovetop Mac & Cheese",
    category: "PASTA",
    time: "16 min",
    cost: "约 US$5.40",
    ingredients: [
      ["通心粉", "120 g", "任何短意面均可"],
      ["切达芝士", "70 g", "刨丝"],
      ["牛奶", "120 ml", "全脂更香"],
      ["黄油", "10 g", "一小块"],
      ["面包糠", "2 汤匙", "可选"],
    ],
    steps: [
      "意面按包装时间煮熟，留半杯煮面水。",
      "原锅小火融化黄油，倒入牛奶加热但不要沸腾。",
      "加入芝士搅至顺滑，过稠就加一点煮面水。",
      "倒回意面拌匀，撒黑胡椒和烤香面包糠。",
    ],
    tip: "关火后再放芝士，酱汁更顺，不容易油水分离。",
  }),
  makeRecipe("US", {
    id: "us-taco-rice",
    image: dishAsset("us-taco-rice.png"),
    title: "鸡肉塔可饭碗",
    english: "Chicken Taco Rice Bowl",
    category: "BOWL",
    time: "22 min",
    cost: "约 US$7.20",
    ingredients: [
      ["鸡腿肉", "180 g", "切小块"],
      ["塔可调料", "1 汤匙", "或辣椒粉加孜然"],
      ["米饭", "1 碗", "隔夜饭也可"],
      ["罐装黑豆", "1/3 罐", "冲洗"],
      ["玉米与莎莎酱", "各 3 汤匙", "现成款"],
    ],
    steps: [
      "鸡肉拌塔可调料，中火煎至边缘焦香。",
      "黑豆与玉米倒入同锅翻热。",
      "米饭加热后铺入碗底，放上鸡肉与豆类。",
      "淋莎莎酱；有酸奶或牛油果可再加一勺。",
    ],
    tip: "多做一份鸡肉，第二天夹进卷饼就是新的一餐。",
  }),
  makeRecipe("US", {
    id: "us-creamy-chicken",
    image: dishAsset("us-creamy-chicken.png"),
    title: "一锅奶油鸡肉意面",
    english: "Creamy Chicken Pasta",
    category: "MAIN",
    time: "25 min",
    cost: "约 US$8.10",
    ingredients: [
      ["鸡胸肉", "150 g", "切片"],
      ["意面", "120 g", "细面或宽面"],
      ["淡奶油", "100 ml", "可换蒸发奶"],
      ["蒜", "2 瓣", "切末"],
      ["冷冻西兰花", "1 杯", "无需解冻"],
    ],
    steps: [
      "鸡肉加盐煎至变色，盛出备用。",
      "原锅炒香蒜末，倒入淡奶油和半杯水。",
      "放意面与西兰花，加盖中火焖煮至面熟。",
      "鸡肉回锅，黑胡椒调味并收浓酱汁。",
    ],
    tip: "酱汁冷却后会变稠，出锅时保留一点流动感。",
  }),

  makeRecipe("UK", {
    id: "uk-tikka",
    title: "快捷玛萨拉咖喱鸡",
    english: "Chicken Tikka Masala",
    category: "CURRY",
    time: "26 min",
    cost: "约 £6.80",
    ingredients: [
      ["鸡腿肉", "180 g", "切块"],
      ["Tikka 咖喱酱", "1/2 罐", "超市现成款"],
      ["原味酸奶", "2 汤匙", "更顺滑"],
      ["巴斯马蒂米", "90 g", "淘洗"],
      ["香菜", "少许", "可选"],
    ],
    steps: [
      "米加 1.5 倍清水，小火煮 12 分钟后关火焖着。",
      "鸡肉中火煎至表面上色。",
      "倒入咖喱酱和少量水，盖盖小火煮 10 分钟。",
      "关火拌入酸奶，与米饭一起装碗。",
    ],
    tip: "酸奶一定关火后再加，既能降辣也不会结块。",
  }),
  makeRecipe("UK", {
    id: "uk-beans-toast",
    image: dishAsset("uk-beans-toast.png"),
    title: "升级版焗豆吐司",
    english: "Loaded Beans on Toast",
    category: "QUICK",
    time: "12 min",
    cost: "约 £3.40",
    ingredients: [
      ["焗豆罐头", "1/2 罐", "番茄味"],
      ["全麦吐司", "2 片", "烤脆"],
      ["鸡蛋", "1 个", "煎或水波"],
      ["切达芝士", "30 g", "刨丝"],
      ["辣酱", "少许", "可选"],
    ],
    steps: [
      "小锅把焗豆加热，撒黑胡椒。",
      "吐司烤脆，同时煎一枚溏心蛋。",
      "焗豆铺在吐司上，趁热撒芝士。",
      "放上鸡蛋和辣酱，切开即食。",
    ],
    tip: "这是赶论文夜的救命菜，纤维和蛋白质都比泡面完整。",
  }),
  makeRecipe("UK", {
    id: "uk-shepherd",
    image: dishAsset("uk-shepherd-pie.png"),
    title: "平底锅牧羊人派",
    english: "Skillet Shepherd's Pie",
    category: "MAIN",
    time: "32 min",
    cost: "约 £7.10",
    ingredients: [
      ["牛肉末", "180 g", "也可用素肉末"],
      ["冷冻杂菜", "1 杯", "豌豆胡萝卜"],
      ["肉汁粉", "1 汤匙", "加水调开"],
      ["即食土豆泥", "1 份", "快捷版本"],
      ["伍斯特酱", "1 茶匙", "提鲜"],
    ],
    steps: [
      "牛肉末煎散，倒掉过多油脂。",
      "加入杂菜、肉汁和伍斯特酱，煮至浓稠。",
      "按包装做好土豆泥，铺在肉酱表面。",
      "盖盖小火焖 5 分钟，撒黑胡椒即可。",
    ],
    tip: "如果有烤箱，把整锅上火烤 5 分钟会多一层焦香。",
  }),

  makeRecipe("CA", {
    id: "ca-salmon",
    title: "枫糖酱油三文鱼",
    english: "Maple Soy Salmon",
    category: "SEAFOOD",
    time: "22 min",
    cost: "约 C$12.40",
    ingredients: [
      ["三文鱼排", "1 块", "约 160 g"],
      ["枫糖浆", "1 汤匙", "纯枫糖更香"],
      ["酱油", "1 汤匙", "普通生抽"],
      ["小土豆", "200 g", "切小块"],
      ["四季豆", "1 把", "去头尾"],
    ],
    steps: [
      "土豆微波 5 分钟至半熟，平底锅煎至金黄。",
      "枫糖浆与酱油混合，抹在三文鱼表面。",
      "鱼排入锅每面煎 3–4 分钟，反复刷酱汁。",
      "四季豆最后入锅炒熟，与鱼和土豆装盘。",
    ],
    tip: "枫糖酱汁容易焦，最后几分钟再刷最稳。",
  }),
  makeRecipe("CA", {
    id: "ca-poutine",
    image: dishAsset("ca-poutine.png"),
    title: "宿舍版肉汁芝士薯条",
    english: "Dorm-room Poutine",
    category: "COMFORT",
    time: "20 min",
    cost: "约 C$7.30",
    ingredients: [
      ["冷冻薯条", "250 g", "空气炸锅或烤箱"],
      ["芝士凝乳", "80 g", "可换马苏里拉块"],
      ["肉汁粉", "1 份", "按包装冲调"],
      ["黑胡椒", "适量", "现磨"],
      ["葱花", "少许", "可选"],
    ],
    steps: [
      "冷冻薯条按包装烤至非常酥脆。",
      "小锅把肉汁煮至比普通酱汁略稠。",
      "热薯条上铺芝士凝乳。",
      "淋滚烫肉汁，撒黑胡椒和葱花马上吃。",
    ],
    tip: "薯条一定烤脆一点，才扛得住肉汁。",
  }),
  makeRecipe("CA", {
    id: "ca-chowder",
    image: dishAsset("ca-corn-chowder.png"),
    title: "奶油玉米浓汤",
    english: "Creamy Corn Chowder",
    category: "SOUP",
    time: "27 min",
    cost: "约 C$6.20",
    ingredients: [
      ["罐装玉米", "1 罐", "沥干"],
      ["土豆", "1 个", "切小丁"],
      ["牛奶", "250 ml", "全脂更浓"],
      ["培根", "2 片", "切碎，可省略"],
      ["洋葱", "1/2 个", "切丁"],
    ],
    steps: [
      "培根煎脆后盛出，用锅中油脂炒软洋葱。",
      "加入土豆、玉米和刚没过食材的水，煮 12 分钟。",
      "压碎一部分土豆和玉米，再倒入牛奶。",
      "小火加热至浓稠，撒培根碎与黑胡椒。",
    ],
    tip: "压碎一部分食材就是不用面粉也能浓稠的秘诀。",
  }),

  makeRecipe("SEA", {
    id: "sea-basil",
    title: "泰式打抛鸡饭",
    english: "Thai Basil Chicken Rice",
    category: "RICE",
    time: "18 min",
    cost: "约 S$5.80",
    ingredients: [
      ["鸡肉末", "180 g", "猪肉末也可"],
      ["罗勒叶", "1 大把", "九层塔最佳"],
      ["鱼露", "1 汤匙", "灵魂调味"],
      ["蒜与小米辣", "各适量", "切碎"],
      ["米饭与鸡蛋", "各 1 份", "搭配"],
    ],
    steps: [
      "热锅多一点油，煎一枚边缘焦脆的荷包蛋。",
      "原锅爆香蒜和辣椒，加入鸡肉末炒散。",
      "加鱼露、少许酱油和糖，大火收汁。",
      "关火前拌入罗勒，盖在米饭上并放鸡蛋。",
    ],
    tip: "罗勒最后 20 秒再放，香味会比久炒更明显。",
  }),
  makeRecipe("SEA", {
    id: "sea-curry-rice",
    image: dishAsset("sea-curry-rice.png"),
    title: "新加坡咖喱杂菜饭",
    english: "Singapore Curry Rice",
    category: "CURRY",
    time: "24 min",
    cost: "约 S$6.40",
    ingredients: [
      ["咖喱块", "2 块", "日式或南洋款"],
      ["鸡腿肉", "150 g", "切块"],
      ["土豆", "1 个", "切小块"],
      ["卷心菜", "2 大把", "切粗丝"],
      ["米饭", "1 碗", "热饭"],
    ],
    steps: [
      "鸡肉煎香，加入土豆翻炒。",
      "加 350 ml 水煮开，放咖喱块搅匀。",
      "小火煮 12 分钟，最后加入卷心菜。",
      "咖喱略浓时关火，浇在热米饭上。",
    ],
    tip: "卷心菜便宜耐放，还能让咖喱自然变甜。",
  }),
  makeRecipe("SEA", {
    id: "sea-lemongrass",
    image: dishAsset("sea-lemongrass-chicken.png"),
    title: "越式香茅鸡",
    english: "Vietnamese Lemongrass Chicken",
    category: "MAIN",
    time: "25 min",
    cost: "约 S$6.90",
    ingredients: [
      ["去骨鸡腿", "180 g", "切块"],
      ["香茅酱", "1 汤匙", "瓶装最方便"],
      ["鱼露", "2 茶匙", "调咸鲜"],
      ["蜂蜜或糖", "1 茶匙", "帮助焦化"],
      ["黄瓜与米饭", "各 1 份", "搭配"],
    ],
    steps: [
      "鸡肉拌香茅酱、鱼露和蜂蜜，腌 10 分钟。",
      "平底锅中高火把鸡肉铺开，不急着翻动。",
      "底面焦香后翻面，加入两勺水焖至熟透。",
      "与米饭和黄瓜片装盘，锅汁淋在米饭上。",
    ],
    tip: "锅够热才能有街头烤肉般的焦边，别一次放太挤。",
  }),

  makeRecipe("CN", {
    id: "cn-tomato-eggs",
    title: "番茄炒蛋",
    english: "Tomato & Egg Stir-fry",
    category: "QUICK",
    time: "12 min",
    cost: "约 ¥8.00",
    ingredients: [
      ["番茄", "2 个", "切滚刀块"],
      ["鸡蛋", "3 个", "加少许盐打散"],
      ["葱", "1 根", "切葱花"],
      ["白糖", "1 茶匙", "平衡酸味"],
      ["米饭", "1 碗", "搭配食用"],
    ],
    steps: [
      "热锅加油，倒入蛋液快速推炒，刚凝固就盛出。",
      "原锅放番茄，中火炒至出汁。",
      "加盐和白糖调味，把鸡蛋倒回锅中。",
      "轻轻翻匀 30 秒，撒葱花后配米饭。",
    ],
    tip: "鸡蛋先盛出再回锅，口感会比一直炒更嫩。",
  }),
  makeRecipe("CN", {
    id: "cn-mapo-tofu",
    title: "麻婆豆腐",
    english: "Mapo Tofu",
    category: "RICE",
    time: "18 min",
    cost: "约 ¥12.00",
    ingredients: [
      ["嫩豆腐", "1 盒", "切 2 cm 小块"],
      ["猪肉末", "80 g", "也可不放"],
      ["郫县豆瓣酱", "1 汤匙", "剁细"],
      ["花椒粉", "1/2 茶匙", "最后撒"],
      ["淀粉水", "3 汤匙", "薄芡"],
    ],
    steps: [
      "豆腐放入淡盐水中小火煮 2 分钟，捞出备用。",
      "锅中炒散肉末，加入豆瓣酱炒出红油。",
      "加半碗水和豆腐，小火煮 5 分钟入味。",
      "分两次淋入淀粉水收汁，撒花椒粉和葱花。",
    ],
    tip: "豆腐下锅后用锅铲推而不是翻，成品不容易碎。",
  }),
  makeRecipe("CN", {
    id: "cn-kung-pao-chicken",
    title: "宫保鸡丁",
    english: "Kung Pao Chicken",
    category: "MAIN",
    time: "22 min",
    cost: "约 ¥16.00",
    ingredients: [
      ["鸡腿肉", "200 g", "切小丁"],
      ["花生米", "2 汤匙", "熟花生"],
      ["干辣椒", "4 个", "剪成段"],
      ["黄瓜", "1/2 根", "切丁"],
      ["酱油、醋、糖", "各适量", "调成宫保汁"],
    ],
    steps: [
      "鸡丁加少许酱油和淀粉抓匀，腌 8 分钟。",
      "热锅滑熟鸡丁，盛出备用。",
      "小火炒香干辣椒，加入黄瓜丁和鸡丁。",
      "倒入宫保汁大火收亮，关火拌入花生米。",
    ],
    tip: "花生最后再放，才能一直保持酥脆。",
  }),
  makeRecipe("CN", {
    id: "cn-yuxiang-pork",
    title: "鱼香肉丝",
    english: "Yu-shiang Shredded Pork",
    category: "MAIN",
    time: "24 min",
    cost: "约 ¥18.00",
    ingredients: [
      ["猪里脊", "180 g", "切细丝"],
      ["木耳", "1 小把", "泡发切丝"],
      ["胡萝卜", "1/2 根", "切细丝"],
      ["豆瓣酱", "1 汤匙", "炒出红油"],
      ["醋、糖、生抽", "各适量", "调鱼香汁"],
    ],
    steps: [
      "肉丝加盐、淀粉和少许油抓匀。",
      "热锅把肉丝滑至变色，先盛出。",
      "炒香豆瓣酱，加入木耳和胡萝卜丝炒软。",
      "肉丝回锅，倒入鱼香汁大火翻匀收汁。",
    ],
    tip: "鱼香味来自糖醋蒜和豆瓣酱，这道菜本身没有鱼。",
  }),
  makeRecipe("CN", {
    id: "cn-potato-pepper",
    title: "青椒土豆丝",
    english: "Potato & Pepper Stir-fry",
    category: "QUICK",
    time: "15 min",
    cost: "约 ¥7.00",
    ingredients: [
      ["土豆", "1 个", "切细丝"],
      ["青椒", "1 个", "切丝"],
      ["蒜", "2 瓣", "切末"],
      ["白醋", "1 茶匙", "保持爽脆"],
      ["干辣椒", "2 个", "可选"],
    ],
    steps: [
      "土豆丝用清水冲洗两遍，洗掉表面淀粉。",
      "热锅爆香蒜末和干辣椒。",
      "放土豆丝大火翻炒 2 分钟，再加青椒。",
      "沿锅边淋白醋，加盐翻匀马上出锅。",
    ],
    tip: "洗掉淀粉并全程大火，土豆丝才会清爽不粘锅。",
  }),
  makeRecipe("CN", {
    id: "cn-yangzhou-fried-rice",
    title: "扬州炒饭",
    english: "Yangzhou Fried Rice",
    category: "RICE",
    time: "16 min",
    cost: "约 ¥12.00",
    ingredients: [
      ["隔夜米饭", "1 大碗", "提前拨散"],
      ["鸡蛋", "2 个", "打散"],
      ["虾仁", "60 g", "可换火腿"],
      ["冷冻杂菜", "1/2 杯", "无需解冻"],
      ["葱花", "1 把", "分两次放"],
    ],
    steps: [
      "热锅炒熟虾仁和杂菜，盛出备用。",
      "锅中补油，倒蛋液后立即加入米饭。",
      "大火把米饭炒散，加入虾仁、杂菜和盐。",
      "沿锅边淋少许生抽，撒葱花翻匀。",
    ],
    tip: "米饭偏干才容易粒粒分明，现煮饭可先摊凉。",
  }),
  makeRecipe("CN", {
    id: "cn-red-braised-pork",
    title: "红烧肉",
    english: "Red-braised Pork Belly",
    category: "COMFORT",
    time: "50 min",
    cost: "约 ¥24.00",
    ingredients: [
      ["五花肉", "300 g", "切麻将块"],
      ["冰糖", "15 g", "炒糖色"],
      ["生抽", "2 汤匙", "调咸鲜"],
      ["老抽", "1 茶匙", "帮助上色"],
      ["姜与八角", "适量", "去腥增香"],
    ],
    steps: [
      "五花肉冷水下锅焯 3 分钟，捞出擦干。",
      "小火融化冰糖至琥珀色，放肉块翻匀。",
      "加入酱油、姜、八角和没过肉的热水。",
      "小火炖 35 分钟，最后开盖收至酱汁浓亮。",
    ],
    tip: "一定加热水，肉质不容易突然收紧变柴。",
  }),
  makeRecipe("CN", {
    id: "cn-hot-sour-soup",
    title: "酸辣汤",
    english: "Hot & Sour Soup",
    category: "SOUP",
    time: "20 min",
    cost: "约 ¥10.00",
    ingredients: [
      ["嫩豆腐", "1/2 盒", "切细条"],
      ["木耳与香菇", "各 1 小把", "泡发切丝"],
      ["鸡蛋", "1 个", "打散"],
      ["香醋", "2 汤匙", "出锅前放"],
      ["白胡椒粉", "1 茶匙", "辣味来源"],
    ],
    steps: [
      "锅中烧开 500 ml 水，放豆腐、木耳和香菇。",
      "加生抽和盐，小火煮 5 分钟。",
      "淋水淀粉调至微稠，再缓慢倒入蛋液。",
      "关火后加入香醋和白胡椒，撒葱花。",
    ],
    tip: "醋和胡椒关火后再放，酸香和辛辣会更鲜明。",
  }),
  makeRecipe("CN", {
    id: "cn-scallion-noodles",
    title: "葱油拌面",
    english: "Scallion Oil Noodles",
    category: "NOODLES",
    time: "15 min",
    cost: "约 ¥6.00",
    ingredients: [
      ["细面", "120 g", "挂面也可"],
      ["小葱", "5 根", "切长段"],
      ["生抽", "2 汤匙", "调味"],
      ["老抽", "1/2 茶匙", "上色"],
      ["白糖", "1 茶匙", "提鲜"],
    ],
    steps: [
      "冷锅放油和葱段，小火慢慢炸至葱变焦黄。",
      "关火加入生抽、老抽和白糖搅匀。",
      "面条煮熟后沥干，保留两勺面汤。",
      "面条拌入葱油酱，过干就加少许面汤。",
    ],
    tip: "葱油可以一次多做，冷藏后拌饭也很好吃。",
  }),
  makeRecipe("CN", {
    id: "cn-pork-cabbage-dumplings",
    title: "白菜猪肉水饺",
    english: "Pork & Cabbage Dumplings",
    category: "DUMPLING",
    time: "35 min",
    cost: "约 ¥20.00",
    ingredients: [
      ["水饺皮", "20 张", "超市现成"],
      ["猪肉馅", "180 g", "二八肥瘦"],
      ["白菜", "150 g", "切碎挤水"],
      ["姜末", "1 茶匙", "去腥"],
      ["生抽与香油", "各 1 汤匙", "调馅"],
    ],
    steps: [
      "肉馅加入生抽、姜末和香油，朝一个方向搅上劲。",
      "拌入挤干水分的白菜碎。",
      "饺子皮包入一勺馅，对折捏紧边缘。",
      "水开下饺子，点两次冷水，全部浮起后捞出。",
    ],
    tip: "包好的生饺子先平铺冷冻，冻硬后再装袋就不会粘。",
  }),
];

export const getRegionRecipes = (recipes, regionId) =>
  recipes.filter((recipe) => recipe.region === regionId);
